line-length = 100
target-version = "py311"
src = ["src", "tests"]

[lint]
select = ["E","F","I","B","UP","S","N","ANN","ARG","C4","DTZ","PIE","PL","PT","RUF"]
ignore = ["ANN101","ANN102"]

[lint.per-file-ignores]
"tests/**.py" = ["S101","ANN201","ANN001","ANN002","ANN003"]
"src/harness/utils/logging.py" = ["S101"]
